"""
Report Generator Module
Generates forensic investigation reports
"""

import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional


class ReportGenerator:
    """Generate forensic investigation reports in various formats"""
    
    def __init__(self):
        """Initialize report generator"""
        self.logger = logging.getLogger(__name__)
        self.data = {}
        
    def generate(self, case_name: str, output_path: str, 
                format: str = 'html') -> str:
        """
        Generate a forensic report
        
        Args:
            case_name: Name of the forensic case
            output_path: Output file path
            format: Report format ('html', 'json', 'txt')
            
        Returns:
            Path to generated report
        """
        self.logger.info(f"Generating {format.upper()} report for case: {case_name}")
        
        if format == 'html':
            return self._generate_html_report(case_name, output_path)
        elif format == 'json':
            return self._generate_json_report(case_name, output_path)
        elif format == 'txt':
            return self._generate_text_report(case_name, output_path)
        else:
            raise ValueError(f"Unsupported report format: {format}")
            
    def add_section(self, title: str, content: Dict):
        """
        Add a section to the report
        
        Args:
            title: Section title
            content: Section content dictionary
        """
        self.data[title] = content
        
    def _generate_html_report(self, case_name: str, output_path: str) -> str:
        """Generate HTML report"""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forensic Report - {case_name}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }}
        .header {{
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 5px;
        }}
        .section {{
            background-color: white;
            margin: 20px 0;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        .badge {{
            display: inline-block;
            padding: 5px 10px;
            background-color: #27ae60;
            color: white;
            border-radius: 3px;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Forensic Investigation Report</h1>
        <p>Case: {case_name}</p>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
"""
        
        # Add sections
        for title, content in self.data.items():
            html += f'    <div class="section">\n'
            html += f'        <h2>{title}</h2>\n'
            
            if isinstance(content, dict):
                html += '        <table>\n'
                for key, value in content.items():
                    html += f'            <tr><th>{key}</th><td>{value}</td></tr>\n'
                html += '        </table>\n'
            elif isinstance(content, list):
                html += '        <ul>\n'
                for item in content:
                    html += f'            <li>{item}</li>\n'
                html += '        </ul>\n'
            else:
                html += f'        <p>{content}</p>\n'
                
            html += '    </div>\n'
        
        html += """    <div class="footer">
        <p>This report was generated by Forensic Disc Recovery Tool</p>
        <p>For official use only - Maintain chain of custody</p>
    </div>
</body>
</html>
"""
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
            
        self.logger.info(f"HTML report saved to: {output_path}")
        return output_path
        
    def _generate_json_report(self, case_name: str, output_path: str) -> str:
        """Generate JSON report"""
        report = {
            'case_name': case_name,
            'generated': datetime.now().isoformat(),
            'tool': 'Forensic Disc Recovery Tool',
            'version': '1.0.0',
            'sections': self.data
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=4)
            
        self.logger.info(f"JSON report saved to: {output_path}")
        return output_path
        
    def _generate_text_report(self, case_name: str, output_path: str) -> str:
        """Generate plain text report"""
        lines = []
        lines.append("=" * 80)
        lines.append("FORENSIC INVESTIGATION REPORT")
        lines.append("=" * 80)
        lines.append(f"Case: {case_name}")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Tool: Forensic Disc Recovery Tool v1.0.0")
        lines.append("=" * 80)
        lines.append("")
        
        for title, content in self.data.items():
            lines.append(f"\n{title}")
            lines.append("-" * len(title))
            
            if isinstance(content, dict):
                for key, value in content.items():
                    lines.append(f"{key}: {value}")
            elif isinstance(content, list):
                for item in content:
                    lines.append(f"  - {item}")
            else:
                lines.append(str(content))
                
            lines.append("")
        
        lines.append("=" * 80)
        lines.append("END OF REPORT")
        lines.append("=" * 80)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
            
        self.logger.info(f"Text report saved to: {output_path}")
        return output_path
        
    def generate_recovery_report(self, recovery_stats: Dict, output_path: str):
        """
        Generate a specialized report for file recovery operations
        
        Args:
            recovery_stats: Recovery statistics dictionary
            output_path: Output file path
        """
        self.add_section('Recovery Summary', {
            'Total Files Recovered': recovery_stats.get('total_files', 0),
            'Total Size (MB)': f"{recovery_stats.get('total_size_mb', 0):.2f}",
            'Largest File': recovery_stats.get('largest_file', 'N/A'),
            'Largest Size (MB)': f"{recovery_stats.get('largest_size', 0) / (1024*1024):.2f}"
        })
        
        # File types breakdown
        file_types = recovery_stats.get('file_types', {})
        if file_types:
            type_data = {}
            for ext, info in file_types.items():
                type_data[ext] = f"{info['count']} files ({info['size'] / (1024*1024):.2f} MB)"
            self.add_section('File Types Recovered', type_data)
            
        return self.generate(
            f"Recovery_{datetime.now().strftime('%Y%m%d_%H%M%S')}", 
            output_path,
            'html'
        )
